### ISSUE TITLE
Getting a 404 from the url

### ISSUE THREAD

**Issue by SirLaffalot** [cweiske/grauphel#11]
On  3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux (Mint 17 distro)

running wdfs from command line:
wdfs -o accept_sslcert -D https://cloud.infoscienceinc.com/index.php/apps/grauphel testGrauphe
wdfs settings:
  program_name: wdfs
  webdav_resource: https://cloud.infoscienceinc.com/index.php/apps/grauphel
  accept_certificate: true
  username: NULL
  password: NULL
  redirect: true
  svn_mode: false
  locking_mode: 0
  locking_timeout: 300
WARNING: untrusted server certificate for 'cloud.infoscienceinc.com':
 certificate is valid from Fri, 27 Jun 2014 07:15:17 GMT to Sat, 27 Jun 2015 07:15:17 GMT
 issued to: InfoScience Inc, Fort Lauderdale, Florida, US
 issued by: InfoScience Inc, Fort Lauderdale, Florida, US
## error: could not mount remote server 'https://cloud.infoscienceinc.com/index.php/apps/grauphel'. reason: 404 Not Found.

(same response with user/pw given)

On the server, log says:
203.217.112.14 - - [12/Oct/2014:17:10:54 +0000] "OPTIONS /index.php/apps/grauphel HTTP/1.1" 404 5754

grauphel version: 2014-10-03

owncloud version : ownCloud 7.0.2 (stable)

Thanks

**Comment by cweiske** [comment]
grauphel is no webdav server, but implements the tomboy REST api.

To set it up, open the tomboy settings -> Synchronization and select "Tomboy web".

**Comment by SirLaffalot** [comment]
Got it, thanks - 
select "Tomboy web" worked
