### ISSUE TITLE
Upgrade problem from 0.2 to 0.4

### ISSUE THREAD

**Issue by jukey** [cweiske/grauphel#12]
I successfully used version 0.2 of grauphel and wanted to upgrade to the current version 0.4:
1. I deleted the 'grauphel' directory within the 'app' directory.
2. I unzipped graupelk in a new folder called 'graupel' at the same place the olde folder was before.
3. I opened the main page of my owncloud installation in the browser. -> There I am asked to perform an update. Once I run thid update I am getting this error message:

> Updating ownCloud to version 7.0.2, this may take a while.
> 
> Wartungsmodus eingeschaltet
> Datenbank-Schemenaktualisierung geprüft
> An exception occurred while executing 'INSERT INTO oc_grauphel_oauth_tokens ("token_id",  token_user, token_type, token_key, token_secret, token_verifier, token_callback) SELECT token_id, token_user, token_type, token_key, token_secret, token_verifier, token_callback FROM __temp__oc_grauphel_oauth_tokens': SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: oc_grauphel_oauth_tokens.token_client
> 
> The update was unsuccessful.Please report this issue to the ownCloud community.

As soon as I delete the grauphel directory again I am able to use owncloud without any issue.

Do you have an idea what is the problem here?
Is there a general upgrade guide for this app?

Thanks and kind regards Uwe

**Comment by cweiske** [comment]
There is no upgrade guide since I don't have any experience doing upgrades with it. I only use the developer version locally.

You could try to delete all tokens in the tokens table and perform the upgrade again. This could make it work.

**Comment by cweiske** [comment]
I could modify the database definition to set a default value for client.

**Comment by cweiske** [comment]
@jukeyju - edit `app/database.xml` and add `<default></default>` in the `token_client` field. Does that help?

Then you do not need to remove the existing tokens.

**Comment by jukey** [comment]
Hi Christian,

tanks for you fast answers. I checkd the `owncloud/app` directory but there seems to be no `database.xml`.

However I found the database.xml in `owncloud/app/grauphel/appinfo/` but I don't know exactely what do you mean by:

> add `<default></default>` in the `token_client` field

Maybe you can show me what you mean by answering here? :-)

Thanks a lot, Uwe

**Comment by cweiske** [comment]
Currently it looks like this:

```
            <field>
                <name>token_client</name>
                <type>text</type>
                <notnull>true</notnull>
                <length>256</length>
            </field>
```

Change it to this:

```
            <field>
                <name>token_client</name>
                <type>text</type>
                <notnull>true</notnull>
                <default></default>
                <length>256</length>
            </field>
```

**Comment by jukey** [comment]
I did the described changes but it doesen't help. I am getting ecxactely the same error message as written above.

Are there information regarding apps stored somewher else? Because I do not do a real upgrade as I deleted the whole folder and extracted your latest version. This sounds more like a fresh and clean installation so I am wondering that you don't get the same error at your installation...

**Comment by cweiske** [comment]
Now also edit appinfo/version and change 0.4.0 to 0.4.1, and do the same in info.xml. Try to upgrade again.

**Comment by jukey** [comment]
I did but got the same error message as before. If you have further ideas please let me know I would love to try them as well. Thanks a lot.

**Comment by cweiske** [comment]
Sorry, I have no more ideas.

Just delete all entries in the tokens table. You have to re-authenticate with all devices then.

**Comment by jukey** [comment]
Hi, I assume the entries should be part of the database.xml file as well?

As I wrote I used your fresh tar.bz2 package that does not contain any token or data I was using before. And I got the error message anyway. :-(

For that reason I am asking if tokens are stored somewhere else. Do you have an Idea where? I assume next time I should deaktivate the app on the owncloud admin page first and unpack the new version afterwards.

How do you upgrade your local installation for testing reason when there is a new version or test candidate?

**Comment by cweiske** [comment]
> As I wrote I used your fresh tar.bz2 package that does not contain any token or data I was using before. And I got the error message anyway. :-(

You still have the _database tables_ and data in them that you used in 0.2

> For that reason I am asking if tokens are stored somewhere else.
> In the database. The XML contains the structure only.
> 
> How do you upgrade your local installation for testing reason when there is a new version or test candidate?
> The same way as you. But I upgraded to 0.3 in the meantime.

**Comment by cweiske** [comment]
```
$ sqlite /path/to/owncloud/data/owncloud.db
DELETE FROM oc_grauphel_oauth_tokens;
```

**Comment by jukey** [comment]
Thank you very much! It worked like a charm so this issue is solved for me. :-)
