### ISSUE TITLE
Checkboxes in Grauphel/Tomboy 

### ISSUE THREAD

**Issue by menelic** [cweiske/grauphel#14]
It would be great to have a checkbox formatting option as offered for example in the "Denkzettel" Android app https://play.google.com/store/apps/details?id=com.silli.notizen&hl=en ? As in where [] is transformed into clickabe checkbox? This question is more about a Tomboy core functionality but since I found discussions online http://osdir.com/ml/gnome.tomboy/2005-02/msg00033.html, but no solution I thought I d ask in the owncloud app forum. I remembered some developers complaining about the comment section there so I came here to open an issue.  I m sure this is of interest for people who consider tomboy/Grauphel as note taking app...thanks in advance!

**Comment by cweiske** [comment]
Adding checkbox support in grauphel alone does not help.
You need support for it in Tomboy as well, which I don't have any influence on.
Plese open a feature request in the tomboy bug tracker at 
https://bugzilla.gnome.org/browse.cgi?product=tomboy

Once checkboxes are defined in the tomboy note format at
https://wiki.gnome.org/Apps/Tomboy/NoteXmlFormat I can implement it in
grauphel.

Note that grauphel is only for viewing notes (unless someone provides a patch
that implements writing as well), so support in grauphel only would not help.

**Comment by cweiske** [comment]
There is already a feature request; https://bugzilla.gnome.org/show_bug.cgi?id=597459

Until that one is implemented I won't do anything here.
