### ISSUE TITLE
installation directions have non-functioning URL

### ISSUE THREAD

**Issue by jmcclelland** [cweiske/grauphel#16]
On the page: http://cweiske.de/grauphel.htm#installation

The installation directions say:
wget http://www.bogo/download/grauphel/grauphel-0.4.0.tar.bz2

However, www.bogo is a non-working URL.

I think it should be:

wget 'http://cweiske.de/download/grauphel/grauphel-0.4.0.tar.bz2'

**Comment by cweiske** [comment]
Fixed. Thanks.
