### ISSUE TITLE
Provide download via https URL

### ISSUE THREAD

**Issue by jmcclelland** [cweiske/grauphel#17]
Please provide a downlink over an URL that can be authenticated and/or provide some kind of checksum so we can verify that we have downloaded what you intended for us to download.

**Comment by cweiske** [comment]
You can access my domain via HTTPS, even authenticated if you trust the CAcert.org root certificate:

> https://cweiske.de/grauphel.htm

I've also added SHA256 checksums on the homepage.

**Comment by jmcclelland** [comment]
Thanks for the quick response! Now I just need to figure out how to install php5-oauth on Debian Wheezy...

**Comment by cweiske** [comment]
```
$ apt-get install php5-oauth
$ /etc/init.d/apache2 restart
```

That's about it.

**Comment by jmcclelland** [comment]
Ah. I see the problem. In wheezy the package is named liboauth-php, in Jessie and on it's called php5-oauth.

**Comment by jmcclelland** [comment]
Oops. Nope. Those are different packages. As far as I can tell, the php5-oauth package is just not available in Debian wheey.

**Comment by cweiske** [comment]
The unstable repository has `php5-oauth`.
