### ISSUE TITLE
Tabs ignored

### ISSUE THREAD

**Issue by thmo** [cweiske/grauphel#19]
As Tomboy doesn't have support for tables, I sometimes use sections formatted in monospace, and then tabs to obtain pseudo tables. In Grauphel, the tabs are not honoured.

The Tomboy HTML export uses `<span style="font-family:monospace">`...`</span>` for monospaced regions, and also sets the `white-space` style to `pre-wrap`, which causes the tabs to be displayed properly by modern browsers.

A similar approach could easily be used by Grauphel. However, it currently uses `nl2br()`, which, in combination with `white-space: pre-wrap`, leads to too many newlines.

As a side note, Grauphel currently uses `<tt>` which will not be supported in HTML5.

**Comment by cweiske** [comment]
Fixed with grauphel version 0.5.1.
