### ISSUE TITLE
Tomboy ciphers

### ISSUE THREAD

**Issue by bastei** [cweiske/grauphel#2]
Thanks for that nice app!

This is slightly off topic, but I didn't find any information about the problem.

The problem is with the SSL ciphers Tomboy supports. I got the following error trying to sync with this app:
`SSL_do_handshake() failed (SSL: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher) while SSL handshaking`

So obviously Tomboy is expecting ciphers that my server doesn't provide. Do you know which ciphers Tomboy supports? I really don't want to activate TLS_RSA_WITH_RC4_128_MD5 only to get the sync running...

Thanks a lot!

**Comment by cweiske** [comment]
You could either ask on the tomboy mailing list http://lists.beatniksoftware.com/listinfo.cgi/tomboy-list-beatniksoftware.com or use wireshark to find out which ciphers tomboy sends to your server as supported. This is probably the quickest solution.

**Comment by bastei** [comment]
OK, for the sake of completeness here are the ciphers supported by Tomboy 1.15.4:

Cipher Suites (13 suites)
Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA (0x0035)
Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA (0x002f)
Cipher Suite: TLS_RSA_WITH_3DES_EDE_CBC_SHA (0x000a)
Cipher Suite: TLS_RSA_WITH_RC4_128_SHA (0x0005)
Cipher Suite: TLS_RSA_WITH_RC4_128_MD5 (0x0004)
Cipher Suite: TLS_RSA_WITH_DES_CBC_SHA (0x0009)
Cipher Suite: TLS_RSA_EXPORT_WITH_RC4_40_MD5 (0x0003)
Cipher Suite: TLS_RSA_EXPORT_WITH_RC2_CBC_40_MD5 (0x0006)
Cipher Suite: TLS_RSA_EXPORT_WITH_DES40_CBC_SHA (0x0008)
Cipher Suite: TLS_RSA_EXPORT1024_WITH_RC4_56_MD5 (0x0060)
Cipher Suite: TLS_RSA_EXPORT1024_WITH_RC2_CBC_56_MD5 (0x0061)
Cipher Suite: TLS_RSA_EXPORT1024_WITH_DES_CBC_SHA (0x0062)
Cipher Suite: TLS_RSA_EXPORT1024_WITH_RC4_56_SHA (0x0064)
