### ISSUE TITLE
Authentication problem on Webfaction

### ISSUE THREAD

**Issue by prasinos** [cweiske/grauphel#20]
Hi,

I have owncloud 8 + grauphel installed on webfaction.
Due to the way Webfaction serves PHP applications [1] I had to use the workaround described in [2].
This works for calendar and file sync, but I think that it messes up oauth/grauphel: when I visit https://OWNCLOUD/index.php/apps/grauphel/api/1.0 I get a JSON document that looks correct, but https://OWNCLOUD/index.php/apps/grauphel/oauth/request_token results in an empty page (with no errors in owncloud.log). The rest of the grauphel app seems to be working OK.
As a result I cannot sync neither with Tomboy (I see 400 Bad Request in the messages) nor with tomdroid.
Is there a workaround?

[1] https://community.webfaction.com/questions/7249/is-possible-http-authentication-with-php
[2] http://theneum.com/blog/owncloud-7-webfaction/

**Comment by cweiske** [comment]
You could try to do the following, given that the auth data are in `$_GET['Authorization']` now:
1. Open `grauphel/lib/oauth.php`
2. Go to line ~162 which reads
   
   ```
   //$_SERVER['REDIRECT_HTTP_AUTHORIZATION'] = $_SERVER['HTTP_AUTHORIZATION'];
   ```
3. Add the following line below:
   
   ```
   $_SERVER['REDIRECT_HTTP_AUTHORIZATION'] = $_GET['Authorization'];
   ```

Now try to authenticate and tell me if that worked.

**Comment by MegaS0ra** [comment]
Hi,

I have the same problem, but on Owncloud 7. (Ether I use Apache module or FastCGI, I have the same issue).
Adding the previous line did not solved it.

Thank you for your help

**Comment by cweiske** [comment]
@MegaS0ra: This line will only help if you have setup the workaround for webfaction as described in the linked documents.

**Comment by prasinos** [comment]
Thanks for answering.

I added the line in lib/oauth.php and still no joy. owncloud.log has errors like:

{"reqId":"cf42ca88ef649344919dabae40b9633e","remoteAddr":"193.92.17.136","app":"PHP","message":"Undefined index: Authorization at \/home\/prasinos\/webapps\/owncloud\/apps\/grauphel\/lib\/oauth.php#164","level":3,"time":"2015-07-23T16:10:28+00:00"}

**Comment by cweiske** [comment]
Sorry, I can't help any further without access to the server.

**Comment by cweiske** [comment]
@prasinos: You can try to replace the contents of `lib/oauth.php` with https://raw.githubusercontent.com/cweiske/grauphel/15b372c9ce79ceb2d3c69247622f8c099f4adf7c/lib/oauth.php

This should make it work.

**Comment by cweiske** [comment]
Version 0.6.1 released which contains the fix for this issue.
