### ISSUE TITLE
Openshift installation

### ISSUE THREAD

**Issue by ajhepple** [cweiske/grauphel#21]
Hi

I'm keen to try Grauphel but my OwnCloud instance is on Red Hat's OpenShift PaaS and I'm struggling to install the oauth package.  I'm not familiar with PHP dependency management but it seems that OpenShift recommends Pear and does not support PECL.

Are Grauphel's dependencies available as Pear packages or can you give any advice on installing Grauphel on OpenShift?

Thanks
Anthony

**Comment by cweiske** [comment]
The pecl OAuth package is a C extension for PHP. It's not available as a userland-only library, sorry.
