### ISSUE TITLE
Unable to connect using IP

### ISSUE THREAD

**Issue by marmistrz** [cweiske/grauphel#23]
I set up owncloud and grauphel on my computer. When I connected via `localhost`, everything worked as expected. Then I wanted to sync via LAN, using the internal IP `192.168.1.4`. It failed on Conboy and Tomboy (N900 and LM 17.2 respectively) 

Are there any ports which need to be freed in my router?

**Comment by cweiske** [comment]
Can you open and use owncloud in your browser by accessing the IP only instead of the hostname?

**Comment by marmistrz** [comment]
Yes.
The problem was that owncloud didn't recognized the IP as  valid. Marking the address as trusted did the trick. I'm closing it, since it's not a grauphel bug. Nevertheless, it might be worth noting it in the doc :)
