### ISSUE TITLE
Slash in notebook name (Tomboy) makes Grauphel fail

### ISSUE THREAD

**Issue by sm8ps** [cweiske/grauphel#24]
I created a notebook on Tomboy with name "LS_11/12", containing a note named "Note3". The note does seem to sync over to Grauphel, because I can acess it from Tomdroid without a problem.

However, when trying to open Tomboy notes the Owncloud web interface, I get the following error:
`Parameter "rawtag" for route "grauphel.gui.tag" must match "[^/]+?" ("system:notebook:LS_11/12" given).`
This is on Owncloud 7.

I would expect Grauphel to handle notebook names the same way that Tomboy does.

**Comment by cweiske** [comment]
Same as #22. I'll fix it in there.

**Comment by sm8ps** [comment]
Great, thanks a lot for your lightning-fast response and thank you very much for this great piece of software!
Cheers!
sm
