### ISSUE TITLE
Error "Archives of type application/x-bzip2 are not supported" when enabling on owncloud 8.1.1

### ISSUE THREAD

**Issue by tlvu** [cweiske/grauphel#26]
To be able to enable the app directly from the apps list, I think the archive have to be .zip, like ownNote for example https://apps.owncloud.com/content/show.php/ownNote+-+Notes+Application?content=168512.

**Comment by tlvu** [comment]
Found a work-around to be able to use the manually downloaded and unpacked archive: In the apps list (owncloud/index.php/settings/apps), click on "Not enabled" and enable grauphel from there.  Do not try to enable grauphel from "Productivity" where it was initially found.

Still for a better user experience, it would be nice that the archive is in .zip format so enabling also works seamlessly in the "Productivity" section.

**Comment by cweiske** [comment]
Do you have an entry in the ownCloud log file about that? Please post it; I suspect something like https://tigr.net/1858/2014/04/01/owncloud-archives-of-type-inode-x-empty-are-not-supported/

**Comment by tlvu** [comment]
This is all I got in the logs

{"reqId":"VfYyaz@qug@1-sDW6Z1YzAAAAAI","remoteAddr":"192.168.xxx.xxx","app":"core","message":"Archives of type application\/x-bzip2 are not supported","level":3,"time":"2015-09-14T02:35:26+00:00"}

**Comment by cweiske** [comment]
Which PHP modules do you have activated? 
`php -m` will give you that list on the command line.

**Comment by tlvu** [comment]
uname -a
Linux centos7-virt-host 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 
01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

rpm -q owncloud-server
owncloud-server-8.1.1-12.1.noarch

sudo -u apache /var/www/html/owncloud/occ app:list | grep grau
- grauphel: 0.5.1

php -v
PHP 5.4.16 (cli) (built: Jun 23 2015 21:17:27)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies

php -m
[PHP Modules]
bz2
calendar
Core
ctype
curl
date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
json
ldap
libxml
mbstring
mhash
OAuth
openssl
pcntl
pcre
PDO
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
zip
zlib

**Comment by tlvu** [comment]
I managed to reproduce this behavior using docker so it will be easy for you to reproduce so then you can test your fix.

![unable-to-enable-grauphel-on-oc811](https://cloud.githubusercontent.com/assets/11966697/9896993/386cb830-5c11-11e5-831c-016426c09f33.png)

Following are instructions to reproduce:
- Start a fresh owncloud 8.1.1 instance

```
docker run -it --name oc owncloud:8.1.1
```
- In a new terminal, enter the container, perform initial configuration steps

```
docker exec -it oc bash
apt-get update; apt-get install -y sudo
sudo -u www-data php occ maintenance:install --database sqlite --database-name "owncloud" --database-user "root" --database-pass "password" --admin-user "admin" --admin-pass "password"
```
- In a new terminal, get the IP of the container so we can point our browser to

```
docker inspect --format '{{ .NetworkSettings.IPAddress }}' oc # mine is 172.17.0.41
```
- Point the browser to http://172.17.0.41, login with admin:password and try to enable grauphel

**Comment by cweiske** [comment]
I had to [enable experimental apps](https://doc.owncloud.org/server/8.1/admin_manual/configuration_server/config_sample_php_parameters.html#apps) from the appstore in my (older) configuration to see it:

```
'appstore.experimental.enabled' => true,
```

**Comment by cweiske** [comment]
Unfortunately, the app installer only allows .zip and .gz files, see https://github.com/owncloud/core/blob/master/lib/private/installer.php#L279

Seems I have to make a pull request.

**Comment by cweiske** [comment]
I've opened a bug report https://github.com/owncloud/core/issues/19181 and made a pull request to fix it - https://github.com/owncloud/core/pull/19182

When it gets merged there is no need to change away from `.bz2` anymore.

**Comment by cweiske** [comment]
The patch is currently in the ownCloud 9 milestone which will be released february next year - too long away.

I've made grauphel available as .gz file.
