### ISSUE TITLE
Weird repeated warning in owncloud.log: array_shift() expects exactly 1 parameter, 2 given at \/var\/www\/html\/owncloud\/apps\/grauphel\/lib\/converter\/html.php#110

### ISSUE THREAD

**Issue by tlvu** [cweiske/grauphel#28]
{"reqId":"VfZfTh5PgEHFEcrSJ4D9jwAAAAM","remoteAddr":"192.168.xxx.xxx","app":"PHP","message":"array_shift() expects exactly 1 parameter, 2 given at \/var\/www\/html\/owncloud\/apps\/grauphel\/lib\/converter\/html.php#110","level":3,"time":"2015-09-14T05:46:54+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/grauphel\/note\/75aa6d2b-44ac-4a86-8b4b-fdcc4399191f"}

owncloud 8.1.1
grauphel 0.5.1
centos 7 (7.1.1503) 
PHP 5.4.16

**Comment by cweiske** [comment]
Could you privately send me the JSON version of `note/75aa6d2b-44ac-4a86-8b4b-fdcc4399191f`?

**Comment by tlvu** [comment]
This warning appears each time I view a note from owncloud web 
interface, for every notes.  So the exact note does not matter.  Here is 
a JSON of another note that has no privacy data so I can safely post it 
here.

```
{
"guid": "77af9db5-307b-44f8-b215-c360d83e96da",
"create-date": "2015-09-15T07:53:13.8061770-04:00",
"last-change-date": "2015-09-15T07:53:13.8360440-04:00",
"last-metadata-change-date": "2015-09-15T07:53:13.8360440-04:00",
"title": "Using \r\nLinks in Tomboy",
"note-content": "Notes in Tomboy can be linked together \r\nby highlighting text in the current note and clicking the \r\n<bold>Link<\/bold> button above in the toolbar.  Doing so will create a \r\nnew note and also underline the note's title in the current \r\nnote.\n\nChanging the title of a note will update links present in other \r\nnotes.  This prevents broken links from occurring when a note is \r\nrenamed.\n\nAlso, if you type the name of another note in your current \r\nnote, it will automatically be linked for \r\nyou.",
"note-content-version": "0.1",
"open-on-startup": false,
"pinned": false,
"tags": [

],
"last-sync-revision": 13
}
```

It is from this url: 
http://host/owncloud/index.php/apps/grauphel/api/1.0/user/note/77af9db5-307b-44f8-b215-c360d83e96da

**Comment by cweiske** [comment]
This was a copy-paste error.
