### ISSUE TITLE
error inserting notes on postgres

### ISSUE THREAD

**Issue by cweiske** [cweiske/grauphel#3]
I get this message in the OC log when I press the sync button in Tomboy.

 Any clues on how to fix this?

```
 {"app":"index","message":"Doctrine\\DBAL\\DBALException: An exception occurred while executing 'INSERT INTO \"oc_grauphel_notes\" (\"note_guid\", \"note_title\", \"note_content\", \"note_content_version\", \"note_create_date\", \"note_last_change_date\", \"note_last_metadata_change_date\", \"note_open_on_startup\", \"note_pinned\", \"note_tags\", \"note_last_sync_revision\", \"note_user\") VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)':\n\nSQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: \"\"","level":4,"time":"2014-09-09T18:31:42+00:00"}
```

From: http://apps.owncloud.com/content/show.php?content=166654

**Comment by nerdy-sam** [comment]
+1, running postgres also :-) have a great vacation!

Doctrine\DBAL\DBALException: An exception occurred while executing 'INSERT INTO "oc_grauphel_notes" ("note_guid", "note_title", "note_content", "note_content_version", "note_create_date", "note_last_change_date", "note_last_metadata_change_date", "note_open_on_startup", "note_pinned", "note_tags", "note_last_sync_revision", "note_user") VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)': SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: ""

**Comment by cweiske** [comment]
Fixed in git master. Will be in release 0.2.0

**Comment by nerdy-sam** [comment]
Confirmed working, THANKS!
