### ISSUE TITLE
Error on Enabling in apps admin

### ISSUE THREAD

**Issue by snowsquizy** [cweiske/grauphel#30]
**\*  This may be caused by previous installation of Grauphel  ***

I have installed the app by following the procedure on 
http://cweiske.de/grauphel.htm#manual

The following error message is given when trying to enable it though

```
An exception occurred while executing
 'CREATE TABLE `oc_grauphel_oauth_tokens`
 (`token_id` BIGINT AUTO_INCREMENT NOT NULL,
  `token_user` VARCHAR(64) DEFAULT NULL,
  `token_type` VARCHAR(16) NOT NULL,
  `token_key` VARCHAR(128) NOT NULL,
  `token_secret` VARCHAR(128) NOT NULL,
  `token_verifier` VARCHAR(128) NOT NULL,
  `token_callback` VARCHAR(2048) NOT NULL,
  `token_client` VARCHAR(256) NOT NULL,
  `token_lastuse` DATETIME NOT NULL,
  PRIMARY KEY(`token_id`)
 )
 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB':
 SQLSTATE[42S01]: Base table or view already exists:
 1050 Table 'oc_grauphel_oauth_tokens' already exists
```

Can you please advise procedure to remove error.  I have backup copies of notes so not worried about losing them.

**Comment by cweiske** [comment]
The issue here seems to be that ownCloud tries to re-create the SQL table although it already exists. ownCloud should only modify the table to add new fields instead.
- Which ownCloud version did you upgrade from?
- Which ownCloud version did you upgrade to?
- Which grauphel version did you have previously?
- Which grauphel version do you try to install now?

This may be the same issue as owncloud/core#14916

**Comment by snowsquizy** [comment]
Owncloud upgrade from 8.0.4  to 8.1.3
Grauphel version 0.5.0 or 0.5.1 to 0.6.1

I did have issues with the Owncloud Upgrade too.
Will review  https://github.com/owncloud/core/issues/14916 and see if it related or the actual issue.

Thanks for you time

**Comment by cweiske** [comment]
owncloud/core#14916 seems to be about custom table prefixes in owncloud. Do you have such a setting?

**Comment by snowsquizy** [comment]
I definitely haven't changed things related to that

**Comment by cweiske** [comment]
Sorry, I have no idea what I could do here.

If you also had troubles upgrading ownCloud itself, the grauphel issue may be an aftermath of this.

Save the grauphel tables as backup, drop them, activate grauphel in owncloud which will re-create the tables, and then import the backup.

**Comment by snowsquizy** [comment]
Please advise procedure to drop required tables.
Thanks

**Comment by cweiske** [comment]
Use a MySQL client to delete the grauphel tables, e.g. the command line mysql client:

```
$ mysql -uownclouddbuser -powncloudpassword ownclouddb
$ DROP TABLE oc_grauphel_notes;
$ DROP TABLE oc_grauphel_oauth_tokens;
$ DROP TABLE oc_grauphel_syncdata;
```
