### ISSUE TITLE
OwnCloud: "Error enabling app" error

### ISSUE THREAD

**Issue by mach-o** [cweiske/grauphel#33]
I am trying to install Grauphel on an original Raspberry Pi Model B.

I'm able to get to the very end of the installation instructions, but when I try to enable Grauphel, rather than getting an error about the PECL oauth extension, I get a popup that simply indicates "Error enabling app" whose title is "Error". 

I then tried installing the PECL oauth extension according to the instructions anyway, which appears to have succeeded, but I still get the same problem enabling Grauphel.

I realize that is very little error information to go on, but I don't know where ownCloud logs are stored, if anywhere. I'm happy to send more details if you can let me know what would be helpful. Thanks!

**Comment by cweiske** [comment]
ownCloud logs are stored in `data/owncloud.log`, but there are also your web server's error log you could check.

To see if the extension is really enabled, create a file with only

```
<?php phpinfo(); ?>
```

in it and put it in the same folder as ownCloud's `index.php`. You'll see of oauth is listed when accessing the file with your browser.

**Comment by mach-o** [comment]
Perfect, thank you! `data/owncloud.log` gave the answer:

`{"app":"core","message":"App \"Grauphel: Tomboy note server\" can't be installed because it is not compatible with this version of ownCloud","level":3,"time":1447542592}`

And indeed, my ownCloud version does seem to be very old:

`$ aptitude versions owncloud`

`Package owncloud:`
`i   4.0.4debian2-3.3                              oldstable                 500`

But I have done all my apt-get updates, upgrades, and dist-upgrades on raspbian wheezy. So I'm not sure why the version is so old, but I'll take my questions from here to a more appropriate forum, unless you happen to have an idea of how to solve this problem that would save me the trouble.

One last suggestion is that it might be better to provide this error to the user in the UI rather than just in the log file.

**Comment by mach-o** [comment]
It turns out I was still on wheezy: upgrading to jessie as we speak.

**Comment by cweiske** [comment]
You should use ownCloud's own apt repository and not rely on debian's own packages.

**Comment by mach-o** [comment]
Great, thanks again! My problems now come at a stage that's much farther along, haha.

When I ran the instructions to install oauth using pecl, I would get no errors at the command line, but the `test.php` file you mentioned above showed no mention of oauth. Instead I simply did `aptitude install php5-oauth`, after which version 1.2.3 of oauth is reported at being installed.

But when I try to sync from ubuntu Tomboy, I repeatedly get a "Failed to synchronize" message stating "Could not synchronize notes. Check the details below and try again." The "details below" is simply a list of note titles and status, which is either empty or shows the synchronization as being successful. Some of the notes are, however, uploaded, although even then successive attempts to sync generate "note conflicts" asking me to rename several notes, despite that I'm syncing only from one source.

Sorry for the repeated questions, but any further insight would be appreciated.

**Comment by cweiske** [comment]
This is not near enough information for me to even speculate about what could be going wrong.

Start tomboy from a terminal and post the output here.

**Comment by mach-o** [comment]
I get this:

[INFO 07:58:41.185] Initializing Mono.Addins
[ERROR 08:00:47.708] Synchronization failed with the following exception: An element with the same key already exists in the dictionary.
  at System.Collections.Generic.Dictionary`2[System.String,Tomboy.Sync.NoteUpdate].Add (System.String key, Tomboy.Sync.NoteUpdate value) [0x00000] in <filename unknown>:0 
  at Tomboy.WebSync.WebSyncServer.GetNoteUpdatesSince (Int32 revision) [0x00000] in <filename unknown>:0 
  at Tomboy.Sync.SyncManager.SynchronizationThread () [0x00000] in <filename unknown>:0

**Comment by cweiske** [comment]
What ownCloud, grauphel and tomboy versions are you using?

**Comment by mach-o** [comment]
OwnCloud is version 8.1.4
Tomboy is version 1.15.4
For Grauphel, I did a wget of version 0.6.1, but installed it through OwnCloud's web interface after enabling the "experimental applications" option, which doesn't give me any version information, and so leads me to wonder if there's some faint chance that what I enabled is another version from some built-in OwnCloud app repository.

**Comment by cweiske** [comment]
The version should be visible, it is for me:
![2015-11-17 grauphel](https://cloud.githubusercontent.com/assets/59036/11215132/0e0f48e0-8d45-11e5-8f0d-349d72a52b15.png)

**Comment by mach-o** [comment]
Ah, yes, sorry. My weary eyes must have missed the small-print light gray. I do indeed have 0.6.1 installed.

**Comment by cweiske** [comment]
I'm using the same versions, and have no issues. I also have no idea of the tomboy internals; the error messages don't tell me anything.

You should better ask for support for tomboy.

**Comment by mach-o** [comment]
Ok, will do. Thanks again for all your help here. I really appreciate it.
