### ISSUE TITLE
wrong scheme in grauphel's URL

### ISSUE THREAD

**Issue by zoide** [cweiske/grauphel#35]
My owncloud instance does https, 

under 'index.php/apps/grauphel' the sync-server URL shown there is http, not https.

Is this supposed to be the case?

thanks,
udo.

**Comment by cweiske** [comment]
grauphel uses the official ownCloud URL generation methods, so I wonder why this does happen at all.
- Which web server do you use?
- How is PHP connected to the webserver? mod_php, php-fpm, fastcgi, ...?

**Comment by zoide** [comment]
Him I'm using

php-fpm with nginx behind a nginx reverse-proxy

Meanwhile, the issue cleared itself up. I hat a reinstall in between.

**Comment by cweiske** [comment]
Could you please post your nginx configuration? May help others if they encounter the same issue.
