### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by di72nn** [cweiske/grauphel#36]
It looks like PHP 7 and/or oauth-2.0.0 (lower versions don't build with PHP 7) break clients' synchronization (tested on Tomboy and Tomdroid).
All I see in logs is: `"GET /index.php/apps/grauphel/api/1.0/ HTTP/1.1" 401 294`.
ownCloud version is 8.2.2. With PHP 5 all was fine.

**Comment by lioman** [comment]
If I call the api with owncloud on PHP7 I get an 400 and `oauth_problem=signature_method_rejected`

**Comment by derastronaut** [comment]
I don't know if this is the same problem but it seems to be pretty similar.

It seems that grauphel only works fine with PHP 5.5 (fastcgi) in my situation. I use Tomboy (1.15.4) under Ubuntu 14.04 and OwnCloud 8.2.2 on shared webhosting (All-Inkl.com).

If I switch to PHP 5.6 (OAuth 1.2.3) Tomboy under Ubuntu doesn't sync. Tomdroid does. The OwnCloud-logs say: Array to string conversion at /www/htdocs/hanswurst/apps/grauphel/lib/oauth.php#133 Same issue if I switch to PHP 7.0.2 (OAuth 2.0).

**Comment by di72nn** [comment]
Building php-oauth from git seems to fix my issue.

I'll leave the issue opened since there are other participants.

**Comment by di72nn** [comment]
php-oauth-2.0.1 fixes it for me. Closing the issue.

**Comment by thmo** [comment]
Hm, here it doesn't work anymore since updating to php7.

Debian 8 with php 7.0.5-1 from dotdeb, owncloud 9.0.1, grauphel 0.6.2, oauth 2.0.1 installed via pecl, and tomboy 1.15.4 (on Fedora).

A call to /index.php/apps/grauphel/oauth/request_token gets a 400 Bad Request, with this body

    94
    oauth_problem=parameter_absent&oauth_parameters_absent=oauth_consumer_key%26oauth_signature%26oauth_signature_method%26oauth_nonce%26oauth_timestamp
    0

although the request itself contained all these fields:

    POST /index.php/apps/grauphel/oauth/request_token HTTP/1.1
    Authorization: OAuth realm="Snowy",oauth_callback="http%3A%2F%2Flocalhost%3A8000%2Ftomboy-web-sync%2F",oauth_consumer_key="anyone",oauth_nonce="...",oauth_signature="...",oauth_signature_method="HMAC-SHA1",oauth_timestamp="...",oauth_version="1.0"
    Content-Type: application/json
    Content-Length: 0
    Host: ...

Any idea what's going wrong here?

**Comment by cweiske** [comment]
@tmho: Please open a new issue for this.
