### ISSUE TITLE
Standalone version

### ISSUE THREAD

**Issue by joshp23** [cweiske/grauphel#39]
So I really love this idea. However, I am not very interested in installing an own-cloud instance in order to implement this. It seems to me like a full blown owncloud install would be a rather heavy handed approach to gain the function of one app. Perhaps someone can help answer a question for me, is there a way to export this so that it runs as a standalone app? or, alternatively, is there a way to strip owncloud down to a very bare-bone, minimal environment to reduce it's footprint, thereby making this install easier to swallow for me?

Thanks

**Comment by cweiske** [comment]
The grauphel software I developed was a standalone application that saved notes into files. You can find the code at http://git.cweiske.de/grauphel-standalone.git/

You can try to run it - it was functional - but I don't know which bugs are still in it. It's also for one user only, and there is no web-based management at all - neither for tokens nor for notes.
