### ISSUE TITLE
Tomboy OS X does not sync

### ISSUE THREAD

**Issue by qirtaiba** [cweiske/grauphel#4]
Tomboy OS X does not sync with grauphel:

https://github.com/tomboy-notes/tomboy.osx

When you try, it tells you "The URL entered https://yourdomain.tld/owncloud/index.php/apps/grauphel is not valid for syncing".

Related: https://github.com/tomboy-notes/tomboy.osx/issues/39

**Comment by cweiske** [comment]
There is nothing I can do about that problem :/
