### ISSUE TITLE
Sync error owncloud 9.0.1 grauphel 0.6.2

### ISSUE THREAD

**Issue by j-4** [cweiske/grauphel#40]
Hi Christian!
Since my owncloud and grauphel upgrade i get an error message on every sync complaining about an missing argument for some constructor. Are you aware of this issue?

{"reqId":"fdsfdsfdsfsdf","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Missing argument 1 for OCA\Grauphel\Lib\TokenStorage::__construct(), called in \/mnt\/data\/www\/owncloud\/apps\/grauphel\/lib\/dependencies.php on line 69 and defined at \/mnt\/data\/www\/owncloud\/apps\/grauphel\/lib\/tokenstorage.php#34","level":3,"time":"timestamp","method":"GET","url":"\/owncloud\/index.php\/apps\/grauphel\/api\/1.0\/user\/notes","user":"--"}

Thanks for this great app... i already feel bad for not maintaining tomdroid properly :-( I really should change this!
Greetings,
Stefan

**Comment by j-4** [comment]
it seems that commit 9e4e2d8d7e92ce4b02098ceb1c437d08e8fbf986 was lost again somehow. :-)

**Comment by cweiske** [comment]
Not list, just not released.

**Comment by j-4** [comment]
perfect!

**Comment by cweiske** [comment]
0.6.3 is out now.
