### ISSUE TITLE
time problem

### ISSUE THREAD

**Issue by affanse** [cweiske/grauphel#41]
OS: opensuse tumbleweed-april 2016 - Kernel 4.5.0

Server: Apache 2.4 - PHP Version 5.6.20 -  Owncloud 9.0.1 - Grauphel 0.6.3

Client: Tomboy Windows and Tomdroid aswell

Trying to register tomboy with grauphel got this error with mysql, tomboy-client said "Server not responding, Try again later".
#1292 - Incorrect datetime value: '2016-05-06T09:27:15+00:00' for column 'token_lastuse' at row 1

Exception: {"Exception":"Doctrine\DBAL\Exception\DriverException","Message":"An exception occurred while executing 'INSERT INTO `oc_grauphel_oauth_tokens`(`token_user`, `token_type`, `token_key`, `token_secret`, `token_verifier`, `token_callback`, `token_client`, `token_lastuse`) VALUES(?, ?, ?, ?, ?, ?, ?, ?)' with params [null, \"temp\", \"rc2e4681974540792\", \"sddcd21c7d1f79cd9\", \"\", \"http:\\/\\/localhost:8000\\/tomboy-web-sync\\/\", \"\", \"2016-05-06T09:27:15+00:00\"]:\n\nSQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2016-05-06T09:27:15+00:00' for column 'token_lastuse' at row 1","Code":0,"Trace":"#0 \/srv\/www\/htdocs\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))\n#1 \/srv\/www\/htdocs\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO `oc...', Array)\n#2 \/srv\/www\/htdocs\/owncloud\/lib\/private\/db\/connection.php(184): Doctrine\\DBAL\\Connection->executeQuery('INSERT INTO`oc...', Array, Array, NULL)\n#3 \/srv\/www\/htdocs\/owncloud\/apps\/grauphel\/lib\/tokenstorage.php(81): OC\DB\Connection->executeQuery('INSERT INTO `*P...', Array)\n#4 \/srv\/www\/htdocs\/owncloud\/apps\/grauphel\/controller\/oauthcontroller.php(266): OCA\Grauphel\Lib\TokenStorage->store(Object(OCA\Grauphel\Lib\Token))\n#5 [internal function]: OCA\Grauphel\Controller\OauthController->requestToken()\n#6 \/srv\/www\/htdocs\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#7 \/srv\/www\/htdocs\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Grauphel\Controller\OauthController), 'requestToken')\n#8 \/srv\/www\/htdocs\/owncloud\/lib\/private\/appframework\/app.php(110): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Grauphel\Controller\OauthController), 'requestToken')\n#9 \/srv\/www\/htdocs\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\AppFramework\App::main('OauthController', 'requestToken', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)\n#10 [internal function]: OC\AppFramework\routing\RouteActionHandler->__invoke(Array)\n#11 \/srv\/www\/htdocs\/owncloud\/lib\/private\/route\/router.php(273): call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)\n#12 \/srv\/www\/htdocs\/owncloud\/lib\/base.php(873): OC\Route\Router->match('\/apps\/grauphel\/...')\n#13 \/srv\/www\/htdocs\/owncloud\/index.php(39): OC::handleRequest()\n#14 {main}","File":"\/srv\/www\/htdocs\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":115}

**Comment by cweiske** [comment]
Thanks for the report.

Fixed in release 0.6.4.
