### ISSUE TITLE
Error during first access: Call to undefined method ... ConnectionWrapper::executeQuery()

### ISSUE THREAD

**Issue by Lakrimar** [cweiske/grauphel#42]
Hi,

I've installed Tomboy without problems but during the first access I get a blank page and the owncloud logfile contains the following information:

`{"app":"PHP","message":"Call to undefined method OC\\DB\\ConnectionWrapper::executeQuery() at \/srv\/www\/ssl\/owncloud\/apps\/grauphel\/lib\/notestorage.php#63","level":3,"time":"2016-06-04T10:20:42+00:00"}`

I'm running Owncloud 7.0.10

Regards
Lakri

**Comment by Lakrimar** [comment]
Upgraded my Owncloud installation to 7.0.15 but without success.

After that I replaced `executeQuery()` by `prepare()` in notestorage.php and tokenstorage.php. With this changes the app showed the startpage. A sync was not possible which could be related to the already solved SSL problem with Mono.

**Comment by cweiske** [comment]
This was a change introduced with commit 9501f181f621e9023a9cb27cbbc85afb2743eeca which fixed ownCloud 9. Apparently it broke ownCloud 7.

You could use grauphel 0.6.1 instead.

I do not want to support multiple ownCloud versions that have different database interfaces.

**Comment by Lakrimar** [comment]
Thanks for your reply. The error also occur in 0.6.1. Nevertheless you're right even owncloud 7 is outdated and an upgrade to a newer version is suitable.
