### ISSUE TITLE
Document oauth setup via .deb package

### ISSUE THREAD

**Issue by mvglasow** [cweiske/grauphel#44]
On Debian and derivatives, the oauth dependency can be satisfied by installing the `php5-oauth` package, which has a couple of advantages over the manual way you describe:
* The first step of the manual procedure, `apt-get install libpcre3-dev php-pear php5-dev`, will, among others, install the full autotools suite—which may not be desirable on a production server
* Installing the .deb package will allow you to benefit from automatic updates—potentially desirable for a security component
* Some people (like me) simply prefer to do as much as possible through .deb packages

It would be great if you could include that method in the installation instructions, next to the PECL way.

**Comment by cweiske** [comment]
Finally done :)

http://cweiske.de/grauphel.htm#installation
