### ISSUE TITLE
Run the App without PHP PECL oauth extension?

### ISSUE THREAD

**Issue by DrAxelbauer** [cweiske/grauphel#45]
Hi!
I am a full hearted user of this app for about 2 years now and still like tomboy stuff…Anyway, i bought myself some webspace but unfortunately i am not able to do the installation routine when it comes to PHP PECL oauth extension, because i am only a costumer and not an admin of the webspace....
Sooo…Is there a way to get the app running without installing oauth? 

Thanks, Benjamin.

**Comment by cweiske** [comment]
No, unfortunately not.

The only way would to use a PHP userland oauth library instead of the PHP extension, but that is a lot of work.

**Comment by DrAxelbauer** [comment]
Means that I have to convince them somehow to do some installation stuff ;) Thanks anyway! Where there is a will, there is a way....
