### ISSUE TITLE
ERROR 404: Not Found when following README instructions

### ISSUE THREAD

**Issue by timeraider4u** [cweiske/grauphel#48]
When following the instructions at https://github.com/cweiske/grauphel#manual-installation wget http://cweiske.de/download/grauphel/grauphel-0.6.4.tar.bz2 results in a 404-error.

shouldn' that be .tar.gz instead of .tar.bz2?

```bash
wget http://cweiske.de/download/grauphel/grauphel-0.6.4.tar.gz
tar xzvf grauphel-0.6.4.tar.gz
rm grauphel-0.6.4.tar.gz
```

**Comment by cweiske** [comment]
Yes. I used to publish both tgz and tbz2, but only few installs support bz2. So I dropped bz2.

**Comment by timeraider4u** [comment]
ah okay, I see
