### ISSUE TITLE
Will grauphel become a nextcloud app?

### ISSUE THREAD

**Issue by traumschule** [cweiske/grauphel#52]
Tomboy is rewritten in FreePascal and a wish is to implement the REST API grauphel uses (tomboy-notes/tomboy-ng#1) or [API-0.2](https://github.com/nextcloud/notes/wiki/API-0.2) (nextcloud/notes#151), or both.

**Comment by cweiske** [comment]
I'm actually using grauphel in nextcloud right now. It is just not listed in the nextcloud app store.

**Comment by georg-mayer** [comment]
Hello,

Tomboy works fine for me with nextcloud 12, but it is one of the apps which are indicated as a problem as they need a version which indicates support for nextcloud 13. I'm not an expert in all of this - but does anybody know what I can do to make tomboy ready for nextcloud 13? I guess it is just a number-value in some of the files, but I'm not sure. 

Thanks!!

**Comment by cweiske** [comment]
I'm currently working on publishing on the nextcloud app store, and maybe will see what's the nc13 problem.

**Comment by georg-mayer** [comment]
This is great news! Thanks a lot!

**Comment by cweiske** [comment]
grauphel is available on the nextcloud appstore now: https://apps.nextcloud.com/apps/grauphel

**Comment by e-alfred** [comment]
Does it support Nextcloud 13 which will be released soon?

**Comment by cweiske** [comment]
Currently the maximum nextcloud version is set to 12. I did not test on 13, and will only do that when I upgrade my server.
