### ISSUE TITLE
Tomboy Notes server not installable in Nextcloud 13 app store (docker)

### ISSUE THREAD

**Issue by all-the-good-ones-are-gone** [cweiske/grauphel#55]
On clicking on [Enable] in the Nextcloud app 'store' in Nextcloud 13 (and previously 12):
App "Grauphel: Tomboy note server" cannot be installed because the following dependencies are not fulfilled: The library OAuth is not available.

I cannot test with a bare install anymore, as I've apparently killed that. Current system is near-copy of example files from https://github.com/nextcloud/docker, using https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm and https://github.com/nextcloud/docker/tree/master/.examples/dockerfiles/full/fpm, setting individual configuration, and modifying the nextcloud Dockerfile (from full above) to include "&& pecl install oauth \". 
Additionally, running "docker-compose exec app pecl install oauth" results in "ecl/oauth is already installed and is the same as the released version 2.0.2".

Is this potentially a misconfiguration on my end, or an issue with grauphel?

**Comment by cweiske** [comment]
It looks like php's oauth extension is installed, but not loaded.

You need to load it in your `php.ini`, by adding `extension=oauth.so`, and then restart php-fpm or the web server.

**Comment by all-the-good-ones-are-gone** [comment]
I found this near the end of the build command output. Maybe an echo command to append a line to a php.ini file somewhere is needed?

>Build process completed successfully
>Installing '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/oauth.so'
>install ok: channel://pecl.php.net/oauth-2.0.2
configuration option "php_ini" is not set to php.ini location
You should add "extension=imagick.so" to php.ini
configuration option "php_ini" is not set to php.ini location
You should add "extension=imagick.so" to php.ini
configuration option "php_ini" is not set to php.ini location
You should add "extension=smbclient.so" to php.ini
configuration option "php_ini" is not set to php.ini location
You should add "extension=imagick.so" to php.ini
configuration option "php_ini" is not set to php.ini location
You should add "extension=smbclient.so" to php.ini
configuration option "php_ini" is not set to php.ini location
You should add "extension=oauth.so" to php.ini
Removing intermediate container 053c77c48f24
---> badd87b92314
Step 3/5 : COPY redis.config.php /usr/src/nextcloud/config/redis.config.php
---> 0a3c3d936b6b
Step 4/5 : COPY supervisord.conf /etc/supervisor/supervisord.conf
---> 937449da653e
Step 5/5 : CMD ["/usr/bin/supervisord"]
---> Running in d8ecd2efdef3
Removing intermediate container d8ecd2efdef3
---> 5bb6d4dacb77
Successfully built 5bb6d4dacb77
Successfully tagged docker_app:latest

**Comment by cweiske** [comment]
Yes. But that's not grauphel's task.

**Comment by monperrus** [comment]
WDYT of https://github.com/nextcloud/docker/pull/1023?

**Comment by monperrus** [comment]
Here is how to activate oauth for grauphel.

Works for me in a Docker container running Nextcloud 23:

```
apt install libpcre3-dev
pecl install oauth
echo extension=oauth.so > /usr/local/etc/php/conf.d/oauth.ini
service apache2 restart
```
