### ISSUE TITLE
Add iOS support by collaborating with TomBox

### ISSUE THREAD

**Issue by sunjam** [cweiske/grauphel#56]
[TomBox](https://itunes.apple.com/us/app/tombox/id791567768?mt=8) is an iOS app offering (ipad and iphone) support for Tomboy, Gnote and Dropbox.  Might be possible to request the app support Grauphel as well.

**Comment by cweiske** [comment]
Feel free to send a mail to the tombox developers. I don't have an iPhone, nor will I ever have one so I'm not interested in that myself.
