### ISSUE TITLE
Nextcloud 14 - drop of deprecated APIs

### ISSUE THREAD

**Issue by MorrisJobke** [cweiske/grauphel#57]
Hi just want to inform you that with 14 we will drop for example `linkTo*` methods of `OCP\Util` nextcloud/server#8811

See the PHPDoc in that class for how to handle this now.

Please also have a look at nextcloud/server#7827 for other dropped methods or use the app:code-check to highlight deprecated methods in the current code.

cc @cweiske

**Comment by MagicFab** [comment]
So far this is the only application that prevents me from upgrading - would love to see it updated to remain compatible.

**Comment by AZtech** [comment]
read this too late. I already upgraded to NC14 and now I'm stuck without this essential app. Any idea when this may be fixed?

**Comment by cweiske** [comment]
Probably next week when when I'm on vacation.

**Comment by MagicFab** [comment]
@cweiske thanks for your work so far! Can you describe what needs to be done? I'll try to get current users to help (including me). I'll take a look at the linked bug report.
This would also be a good time to setup donation links at http://cweiske.de/ :) I'd suggest registering at https://liberapay.com/ and getting a Bitcoin address if you haven't already.

**Comment by MagicFab** [comment]
[This](https://github.com/nextcloud/server/pull/8811#pullrequestreview-103721852) shows the changes needed in grauphel/templates.

**Comment by joshp23** [comment]
I opened #66 which attempts to address the issue.

**Comment by cweiske** [comment]
grauphel 0.7.0 has been released, which brings support for Nextcloud 14: http://cweiske.de/grauphel.htm#download
