### ISSUE TITLE
Editing notes

### ISSUE THREAD

**Issue by joshp23** [cweiske/grauphel#58]
I understand that you have[ little to no interest](https://github.com/cweiske/grauphel#what-is-missing) in working on this, but this is a feature that I would _love_ to have, and I don't mind putting in some time on it! 

I was hoping this issue could act as a place for some guidance to help speed the process along(?). 

---------------------------------

It appears as if you just pull the note data out of the database and throw it out into HTML. This suggests that a simple WYSIWYG javascript editor might only have to get a hold of the text from the database, edit it as html, and then convert the tags to the tomboy format when saving. I assume there is already a mechanism to handle conversions(?).

does this sound like I am on the right track here?

**Comment by joshp23** [comment]
I have been working with the highly customizable [QuillJS](https://quilljs.com/) and I have a nice looking note editor interface:  

![screenshot from 2018-05-05 00-51-47](https://user-images.githubusercontent.com/7341917/39659791-cf2e2086-4ffe-11e8-9b03-57d36539dffe.png)

This would be nice as an overlay popup, like the basic text editor or markdown editor in NextCloud, but I will be happy to have it merely open a new page within NextCloud, replacing the current note display page with the above.

This code should be able to save as you type, which is nice. Clearly I need to add the `add`, `edit` and `delete` buttons to the grauphel note display page, add triggers to populate the editor with appropriate data, and configure endpoints to save the data.

Any input is appreciated.

**Comment by cweiske** [comment]
Yes, for nextcloud integration the editor "just" needs to get hold of the HTML/markup, display it and then for saving, convert it back to the tomboy markup format.

What needs to be kept in mind is that the synchronization revisions need to be incremented when a note is added/saved/deleted.

There is already code to convert tomboy markup to HTML, but no code to convert it back:
- `lib/converter/html.php`
- `lib/converter/cleanhtml.php`

----

My initial idea was to have a complete javascript tomboy rest api client that could then be used without any changes to the current code (because the API is complete) - but this is really much work, compared to the points outlined above.

**Comment by joshp23** [comment]
For clarity: the note revision needs to be updated, this is no problem, but does the user revision counter need to be incremented as well, or should that only happen on external sync calls?

I'm happy to reverse engineer some conversion code :) thanks for pointing out their loc.

**EDIT** It appears as if every change to the DB will require the `latest-sync-revision` to be incremented.

**Comment by cweiske** [comment]
Yes, the `latest-sync-revision` needs to be updated. Not sure about `syncdata_current_sync_guid`, I think it would also need to be changed.

Local changes need to be treated the same way as remote client changes in terms of sync variables.

**Comment by joshp23** [comment]
I have made headway with the delta rendering from quilljs. [Here](https://github.com/joshp23/denote.js) is the tool.

**Comment by cweiske** [comment]
Did you make any progress on the note editing tool? If not, then I'd close this issue.

**Comment by joshp23** [comment]
I had to put this down and have not had an opportunity to pick it up in some time.
