### ISSUE TITLE
jquery-1.10.0.min.map missing

### ISSUE THREAD

**Issue by HorstBrack** [cweiske/grauphel#6]
Hi,

I have the problem that I can not read or write notes in the web interface.
I can see the list of notebooks I created in Tomboy but when I click on one nothing happens.
They are full of notes and all work in tomboy.
Browsers developer console tells me that 
core/js/jquery-1.10.0.min.map is missing.
Indeed, it is not there and it is not included in the zip file I can download here either.
Any clue if this is connected? And if so, where I get this map from?

Thanks a lot in advance!

**Comment by cweiske** [comment]
Chrome devtools try to load the `.map` files. That's nothing bad that they are not there.

Please read the readme at https://github.com/cweiske/grauphel#status - I wrote there:

> Web interface to view notes is missing
