### ISSUE TITLE
nextcloud 13 - grauphel limited to groups

### ISSUE THREAD

**Issue by muwaka** [cweiske/grauphel#61]
hello,

when i try to limit grauphel to groups, it stops working. when visiting [cloud-instance]/apps/grauphel and also [cloud-instance]/apps/grauphel/api/1.0 via the browser they are returning:

Access denied
App is not enabled

Solution is to allow grauphel for all users, but.. well..

thank you for your work and greets,
muwaka

**Comment by cweiske** [comment]
Yes, this is noted in the README:

> grauphel needs to be activated for all users. It will not work with the "enable only for specific groups" setting.

https://github.com/cweiske/grauphel#installation
