### ISSUE TITLE
https://[URL]/index.php/apps/grauphel shows installed apps icons, should redirect to login

### ISSUE THREAD

**Issue by MagicFab** [cweiske/grauphel#62]
https://[URL]/index.php/apps/grauphel shows the following:

![screenshot](https://user-images.githubusercontent.com/317514/46353056-41851680-c629-11e8-9e6b-e0c82fa89cbd.png)

This discloses which apps have been installed, it should redirect to the login page instead (when not logged in).

**Comment by cweiske** [comment]
This is unfortunately not possible, because Tomboy makes an unauthenticated request to the server at first.

**Comment by MagicFab** [comment]
Can that request be singled out by looking at the useragent (or lack of it)?

**Comment by cweiske** [comment]
Maybe, but that would be flaky because different clients use different user agents. New clients would be forced to simulate one of the existing ones.
