### ISSUE TITLE
Initial sync with Tomdroid not working / emoji utf8 problem

### ISSUE THREAD

**Issue by sm8ps** [cweiske/grauphel#64]
First off, many thanks for making Grauphel available! I have used it on OwnCloud for years and want to migrate my notes to NextCloud 13.0.5. The current version of my notes stack is held by Tomdroid 0.7.5 on Android 5.0. The initial sync correctly from Tomdroid (to an empty Nextcloud Grauphel stack) creates an access token which is visible on the Grauphel page in NextCloud. After that it throws an error similar to "error sending note to online synchronisation". A successive sync attempt says "synchronisation is already running" which I believe is due to a time-out. Because after a while (approximately 5 minutes) it re-connects and correctly updates the access time of the token but repeats the same behavior.
The NextCloud log shows the following entry:
```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_grauphel_notes` (`note_guid`, `note_title`, `note_content`, `note_content_version`, `note_create_date`, `note_last_change_date`, `note_last_metadata_change_date`, `note_open_on_startup`, `note_pinned`, `note_tags`, `note_last_sync_revision`, `note_user`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["8f5959f5-b7a1-4e69-8275-3ce2d1da6c14", "Schau dir &quot;Math calculation of a cat to jump but failed \ud83d\ude02\ud83d\ude02&quot; auf YouTube an", "https:\/\/youtu.be\/tN5KIUNfYGA", "0.1", "2000-01-01T00:00:00.0000000+01:00", "2018-07-01T21:04:38.0000000+00:00", "2018-07-01T21:04:38.0000000+00:00", 0, 0, "[]", 1, "stefan"]: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x98\x82\xF0\x9F...' for column 'note_title' at row 1
0.     /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 128: Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
1.    /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php - line 855: Doctrine\DBAL\DBALException driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO `oc...', Array)
2.    /var/www/nextcloud/lib/private/DB/Connection.php - line 195: Doctrine\DBAL\Connection->executeQuery('INSERT INTO `oc...', Array, Array, NULL)
3.    /var/www/nextcloud/apps/grauphel/lib/notestorage.php - line 363: OC\DB\Connection->executeQuery('INSERT INTO `oc...', Array)
4.    /var/www/nextcloud/apps/grauphel/controller/apicontroller.php - line 305: OCA\Grauphel\Lib\NoteStorage->save(Object(stdClass))
5.    /var/www/nextcloud/apps/grauphel/controller/apicontroller.php - line 220: OCA\Grauphel\Controller\ApiController->handleNoteSave('stefan', Object(OCA\Grauphel\Lib\SyncData))
6.    [internal function] OCA\Grauphel\Controller\ApiController->notesSave('stefan')
7.    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 161: call_user_func_array(Array, Array)
8.    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 91: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Grauphel\Controller\ApiController), 'notesSave')
9.    /var/www/nextcloud/lib/private/AppFramework/App.php - line 115: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Grauphel\Controller\ApiController), 'notesSave')
10.    /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('ApiController', 'notesSave', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
11.    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
12.    /var/www/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
13.    /var/www/nextcloud/lib/base.php - line 999: OC\Route\Router->match('/apps/grauphel/...')
14.    /var/www/nextcloud/index.php - line 42: OC handleRequest()
15.    {main}
```
The database remains empty. Does that give any useful information?

**Comment by cweiske** [comment]
> 1366 Incorrect string value: '\xF0\x9F\x98\x82\xF0\x9F...' for column 'note_title' at row 1

The title of that one note ("Schau dir Math calculation of a cat to jump but failed") seems to be strange/broken.

Could you paste its real title here?

**Comment by sm8ps** [comment]
Thanks for your immediate response! You were right on the problem. The title indeed contains Unicode characters (smileys). I have deleted them and now the synchronization went through in mere seconds (~1900 notes!). I had got stuck at "datetime format", wondering if it was a formatting compatibility issue.

**Comment by cweiske** [comment]
For smileys, your database tables would need to have a utf8 mb4 charset like "utf8mb4_unicode_ci".

I might be able to change that in `/appinfo/database.xml`.

**Comment by sm8ps** [comment]
This is beyond my knowledge. I remember reading something about Unicode characters in filenames when setting up MariaDB for Nextcloud but I thought: "who would ever need that?!". I hold by this with a 1:1900 margin of error ... :)

**Comment by cweiske** [comment]
It seems Nextcloud 11 supports utf8mb4 already https://github.com/nextcloud/server/pull/1773.
Now we need to find out how to enable this for the extension.

**Comment by cweiske** [comment]
It works if your database (and tables) is configured to use an utf8mb4 charset.
