### ISSUE TITLE
php extension oauth required

### ISSUE THREAD

**Issue by jukey** [cweiske/grauphel#7]
I am running owncloud on top of an ubuntu 14.04 server. I already installed the package php5-oauth via apt-get. However I always will get this error message if I click on the tomboy notes icon on owncloud:
PHP extension "oauth" is required

However there is still an other package available called:
php-horde-oauth - Horde OAuth client/server

I assume this is not the package I need to install?

Do you have an Idea how to figure out what to do in order to investigate this problem?

**Comment by jukey** [comment]
A reboot of the server solves this issue. now it seems to work. Sorry for the noise. :)

**Comment by cweiske** [comment]
Simply restarting apache/nginx/lighttpd suffices.
