### ISSUE TITLE
Please update for NextCloud 16

### ISSUE THREAD

**Issue by noci2012** [cweiske/grauphel#72]
As it is out now?

**Comment by cweiske** [comment]
Yes, this is that way because I did not test on NC 16 yet.
You could help by trying the version on NC16 yourself:

1. Download the `.tar.gz` file from http://cweiske.de/grauphel.htm#download
2. Extract it in your `nextcloud/apps/` directory
3. Adjust `appinfo/info.xml` to have a nextcloud `max-version` of 16
4. Enable grauphel in the nextcloud apps manager
5. Test it
6. Report back, so that I can either fix the issues you found or increase the max version and re-release grauphel.

(Instructions taken from https://github.com/cweiske/grauphel/issues/54#issuecomment-361166105)

**Comment by noci2012** [comment]
My problem is i can upgrade ..... and not downgrade again, so failure will fail nextcloud.

**Comment by noci2012** [comment]
After update:

Statistics
Number of notes
0
Number of registered apps
0
Sync revision
-1

(Browser cache has been cleared), service side cache has been cleared  (maintenance:repair).
There should be notes according to the TomDroid client, so the counts are off. (I have 3 clients for this account, Phone, Phablet[old], Tablet)
Also selecting tags on the left shows empty page

**Comment by noci2012** [comment]
```
MariaDB [nextcloud]> select count(*) from oc_grauphel_notes ;
+----------+
| count(*) |
+----------+
|       18 |
+----------+
1 row in set (0.00 sec)
MariaDB [nextcloud]> select count(*) from oc_grauphel_oauth_tokens ;
+----------+
| count(*) |
+----------+
|        3 |
+----------+
1 row in set (0.00 sec)

MariaDB [nextcloud]> select count(*) from oc_grauphel_syncdata ;
+----------+
| count(*) |
+----------+
|        2 |
+----------+
1 row in set (0.00 sec)

```

**Comment by noci2012** [comment]
The apps on the phone/table seem to work though

**Comment by gppixelworks** [comment]
Is sync with TomDroid functional with Grauphel version 0.7.1 when installed with Nextcloud v16.x?

I ask as I can more easily deal with Grauphel not displaying Tomboy/Droid notes inside Nextcloud but will not upgrade to Nextcloud 16.x if sync to phone doesn't work.

**Comment by michalzxc** [comment]
Authentication from Tomboy or Tomdroid doesn't work any more with Nextcloud16

I see all the notes what were already synced correctly from Nextcloud Web

```Jun 03 16:52:33 megumin tomboy.desktop[1944]: [ERROR 16:52:33.069] Caught exception. Message: The remote server returned an error: (401) Unauthorized.
Jun 03 16:52:33 megumin tomboy.desktop[1944]: [ERROR 16:52:33.074] Stack trace for previous exception:   at System.Net.HttpWebRequest.GetResponseFromData (System.Net.WebResponseStream stream, System.Threading.CancellationToken cancellationToken) [0x0017e] in <a9a08e39ba304bd0a84c49bd158dfc02>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x00118] in <a9a08e39ba304bd0a84c49bd158dfc02>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at System.Net.HttpWebRequest.GetResponse () [0x00019] in <a9a08e39ba304bd0a84c49bd158dfc02>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at Tomboy.WebSync.Api.OAuth.MakeWebRequest (OAuth.RequestMethod method, System.String url, System.Collections.Generic.List`1[T] parameters, System.String postData) [0x000f2] in <5f006a6f921e44bbbcda8ee13e434ddc>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]: [ERROR 16:52:33.075] Rest of stack trace for above exception:   at System.Environment.get_StackTrace () [0x00000] in <d0e12f672b88444ab4b6d9b2ecf20142>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at Tomboy.WebSync.Api.OAuth.MakeWebRequest (OAuth.RequestMethod method, System.String url, System.Collections.Generic.List`1[T] parameters, System.String postData) [0x00000] in <5f006a6f921e44bbbcda8ee13e434ddc>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at Tomboy.WebSync.Api.OAuth.WebRequest (OAuth.RequestMethod method, System.String url, System.String postData) [0x00000] in <5f006a6f921e44bbbcda8ee13e434ddc>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at Tomboy.WebSync.Api.OAuth.Post (System.String uri, System.Collections.Generic.IDictionary`2[TKey,TValue] queryParameters, System.String postValue) [0x00000] in <5f006a6f921e44bbbcda8ee13e434ddc>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at Tomboy.WebSync.Api.OAuth.GetAuthorizationUrl () [0x00000] in <5f006a6f921e44bbbcda8ee13e434ddc>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at Tomboy.WebSync.WebSyncPreferencesWidget.OnAuthButtonClicked (System.Object sender, System.EventArgs args) [0x00000] in <5f006a6f921e44bbbcda8ee13e434ddc>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at System.Reflection.MonoMethod.InternalInvoke (System.Reflection.MonoMethod , System.Object , System.Object[] , System.Exception& ) [0x00000] in <d0e12f672b88444ab4b6d9b2ecf20142>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <d0e12f672b88444ab4b6d9b2ecf20142>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <d0e12f672b88444ab4b6d9b2ecf20142>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x00000] in <d0e12f672b88444ab4b6d9b2ecf20142>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00000] in <d0e12f672b88444ab4b6d9b2ecf20142>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <d0e12f672b88444ab4b6d9b2ecf20142>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at GLib.Signal.ClosureInvokedCB (System.Object o, GLib.ClosureInvokedArgs args) [0x00000] in <5a439e0caae7469886e7119d9f6bc621>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at GLib.SignalClosure.Invoke (GLib.ClosureInvokedArgs args) [0x00000] in <5a439e0caae7469886e7119d9f6bc621>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at GLib.SignalClosure.MarshalCallback (System.IntPtr raw_closure, System.IntPtr return_val, System.UInt32 n_param_vals, System.IntPtr param_values, System.IntPtr invocation_hint, System.IntPtr marshal_data) [0x00000] in <5a439e0caae7469886e7119d9f6bc621>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at Gtk.Application.gtk_main () [0x00000] in <7a41aae9f05e45b7b5a8cedfab67f8ff>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at Gtk.Application.Run () [0x00000] in <7a41aae9f05e45b7b5a8cedfab67f8ff>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at Tomboy.GnomeApplication.StartMainLoop () [0x00000] in <df08e21f8dff48f1b67600913dd29928>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at Tomboy.Application.StartMainLoop () [0x00000] in <df08e21f8dff48f1b67600913dd29928>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at Tomboy.Tomboy.StartTrayIcon () [0x00000] in <df08e21f8dff48f1b67600913dd29928>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at Tomboy.Tomboy.Main (System.String[] args) [0x00000] in <df08e21f8dff48f1b67600913dd29928>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]: [ERROR 16:52:33.080] Failed to get auth URL from https://sync.unsafe.pl/index.php/apps/grauphel. Exception was: System.Net.WebException: The remote server returned an error: (401) Unauthorized.
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at System.Net.HttpWebRequest.GetResponseFromData (System.Net.WebResponseStream stream, System.Threading.CancellationToken cancellationToken) [0x0017e] in <a9a08e39ba304bd0a84c49bd158dfc02>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x00118] in <a9a08e39ba304bd0a84c49bd158dfc02>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at System.Net.HttpWebRequest.GetResponse () [0x00019] in <a9a08e39ba304bd0a84c49bd158dfc02>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at Tomboy.WebSync.Api.OAuth.MakeWebRequest (OAuth.RequestMethod method, System.String url, System.Collections.Generic.List`1[T] parameters, System.String postData) [0x00177] in <5f006a6f921e44bbbcda8ee13e434ddc>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at Tomboy.WebSync.Api.OAuth.WebRequest (OAuth.RequestMethod method, System.String url, System.String postData) [0x00149] in <5f006a6f921e44bbbcda8ee13e434ddc>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at Tomboy.WebSync.Api.OAuth.Post (System.String uri, System.Collections.Generic.IDictionary`2[TKey,TValue] queryParameters, System.String postValue) [0x0000b] in <5f006a6f921e44bbbcda8ee13e434ddc>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at Tomboy.WebSync.Api.OAuth.GetAuthorizationUrl () [0x00008] in <5f006a6f921e44bbbcda8ee13e434ddc>:0
Jun 03 16:52:33 megumin tomboy.desktop[1944]:   at Tomboy.WebSync.WebSyncPreferencesWidget.OnAuthButtonClicked (System.Object sender, System.EventArgs args) [0x0026a] in <5f006a6f921e44bbbcda8ee13e434ddc>:0```

**Comment by gppixelworks** [comment]
Thanks for the syncing information on Nextcloud 16 and Grauphel.

**Comment by noci2012** [comment]
HM. adding notes on my android does increase the count in tables.
(although the nextcloud / web interface shows nothing). 

So synching does work on my phone.
(adding a new topic i mean).

You may need to setup access tokens if 2FA is used. 
This seems to be the source for that error:
[ERROR 16:52:33.080] Failed to get auth URL from https://sync.unsafe.pl/index.php/apps/grauphel. Exception was: System.Net.WebException: The remote server returned an error: (401) Unauthorized.

**Comment by gppixelworks** [comment]
@noci2012 So currently Grauphel with Nextcloud v16 will properly sync between phones but the web interface for Grauphel within Nextcloud isn't currently functional?

You mentioned that 'adding a new topic' synced.  Does an edit to an existing topic also get synced?

As don't use the web interface too often, I can live with Grauphel only syncing between Tomdroid and Tomboy.  This syncing function is all that is keeping me from upgrading Nextcloud to v16.

**Comment by michalzxc** [comment]
It stopped working with my Tomdroid after upgraded Nextcloud to 16 as well

Message when I try sync: "Error parsing response from Online Synchronization"

**Comment by noci2012** [comment]
i have tomdroid on a phone and on a tablet.
Any update on the phone. after syncing this from the phone to Nextcloud does work.
Syncing on tablet gets me the same version as on the phone, changing this on the tablet.
After syning this to the server the i can see the changes on the phone again after opening the topic again.

So imho the API works. The presentation ON the server web GUI fails.

**Comment by noci2012** [comment]
yesterday added  tomdroid to a new phone and it synced after authentication was done correctly.

**Comment by richard-dg** [comment]
Hi @cweiske, 

I hope your're well. I kindly want to ask, if there is any further development planned or if the project is discontinued?

Thanks a lot.

Richard

**Comment by cweiske** [comment]
I expect a new release end of next week.

This will be the last release, since I'm fed up with the constantly changing API in the bi-yearly nextcloud releases.

**Comment by richard-dg** [comment]
Thanks for the info, which of course is sad but understandable. And thanks for providing this great piece of software for such a long time! As I am not a developer, I cannot offer to continue the project for you. But maybe somebody else will.

**Comment by cweiske** [comment]
Locally I'm stuck with one problem that @michalzxc also seems to have:
Tomboy says
> System.Net.WebException: The remote server returned an error: (401) Unauthorized.

Wireshark told me the underlying error is in 
> POST /index.php/apps/grauphel/oauth/request_token

which gets an invalid signature error:
> oauth_problem=signature_invalid&debug_sbs=POST&%01%3A%2F%2F%01%01&oauth_callback...

But this is probably because I use PHP 7.3.6-1 and php-oauth 2.0.2, which are incompatible ([2.0.4 has a fix](http://git.php.net/?p=pecl/web_services/oauth.git;a=commit;h=0828b70df7606b599785b3de1c15248d3e463b95))
So this is a Debian problem for now -> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=934167

I need to fix this first and then see what real problem is there.
Btw, the web UI works here.

**Comment by cweiske** [comment]
After compiling php-oauth 2.0.4 myself, everything works:
- Setting up fresh sync with tomboy
- Syncing
- Using the web UI
- Searching in nextcloud

**Comment by cweiske** [comment]
grauphel 0.7.2 is out now, which has NextCloud 16 compatibility. No code changes were neccessary.

**Comment by richard-dg** [comment]
Thanks @cweiske!

**Comment by michalzxc** [comment]
Amazing, thank you!
It was exactly the same Debian php-oauth version problem on my side

**Comment by noci2012** [comment]
wrt. API changs, Nextcloud seems to announce them still and giving a deadline..., OwnCloud just moved... 
Thanks for the tools & the update though.

**Comment by marcjohnen** [comment]
Could you be so kind to give me some hints on how to compile oauth 2.0.4 on ubuntu? I'm kind of lost on that.
Thanks

What I did was download http://git.php.net/?p=pecl/web_services/oauth.git;a=snapshot;h=b7009ff6ed9d4a505d4d343e4436d52db3aee102;sf=zip
Follow the instructions in INSTALL and link it in /etc/php/7.3/apache2/php.ini with
the entry extension=/usr/lib/php/20180731/oauth.so

with no change and no error message.

**Comment by cweiske** [comment]
> with no change and no error message.

Create a .php file with contents `phpinfo();` and open it in your browser. php-oauth must show version 2.0.4.

**Comment by marcjohnen** [comment]
Thanks, being quite ignorant to php, I think I forgot to relod and restart php7.3-fpm.
Also I took the the latest version from https://git.php.net/repository/pecl/web_services/oauth.git now.
Thanks for developing grauphel.

**Comment by michalzxc** [comment]
I didn't complied anything, just switched to debian testing (bullseye)

https://mysources.co.uk/docker/debian/raw/master/builder/Dockerfile
https://mysources.co.uk/docker/php/raw/master/builder/Dockerfile

And it works

**Comment by ramcq** [comment]
In case anyone finds themselves here, and is running Debian buster and not easily able to switch to testing, I was able to fix relatively easily.

The latest version of php-oauth in bullseye (currently 2.0.5+1.2.3-1+b1) depends on PHP 7.4 so isn't trivially installable on buster via apt pinning etc.

However, the previous version (2.0.5+1.2.3-1, I guess before a mass rebuild) is still binary compatible with buster and PHP 7.3, so I was able to fetch the binary from snapshot and install directly:

http://snapshot.debian.org/package/php-oauth/2.0.5%2B1.2.3-1/#php-oauth_2.0.5:2b:1.2.3-1

**Comment by monperrus** [comment]
this issue can be closed, grauphel works on latest Nextcloud 23
