### ISSUE TITLE
Nextcloud 17

### ISSUE THREAD

**Issue by richard-dg** [cweiske/grauphel#73]
Hi,

as Nextcloud 17 is out now, I tried to get grauphel to work in the new version. What I did:

- On nextcloud 16 I changed  `<nextcloud min-version="13" max-version="16"/>` to   `<nextcloud min-version="13" max-version="17"/>` in the file `apps/grauphel/appinfo/info.xml`.
- I ran the nextcloud upgrade via web-updater
- After the successful update everything seemed fine
- I created a new note in Tomboy and forced a sync --> seemed fine

Is there anything, which I should consider, test, or change or is is safe to assume that I can upgrade my productive nextcloud and continue using grauphel?

Thanks, 

Richard

**Comment by h1618** [comment]
confirming function on nextcloud 17: after setting max-version to 17 everything runs smooth - syncing with Tomdroid, Tomboy 1.15.4 on Linux and Tomboy 1.15.9 on Windows works in both directions. I have no objections to mark it nextcloud 17 ready.

**Comment by cweiske** [comment]
(could not upload yet because of server error at apps.nextcloud.com)

**Comment by cweiske** [comment]
Uploaded now: https://apps.nextcloud.com/apps/grauphel/releases?platform=17#17
