### ISSUE TITLE
Switch to changelog format recognized by apps.nextcloud.com

### ISSUE THREAD

**Issue by aszlig** [cweiske/grauphel#75]
Right now whenever a new version is released, the changelog is not shown.

The reason for this is that `apps.nextcloud.com` only recognizes the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) format, see here for the corresponding documentation:

https://nextcloudappstore.readthedocs.io/en/latest/developer.html#changelog

**Comment by cweiske** [comment]
The README is already in .rst format, and I will not introduce a second markup format in this repository. I will also not convert the readme for no reason to .md.

Plus my editor has nice ChangeLog format support, but no keep-a-changelog support.

**Comment by aszlig** [comment]
@cweiske: This was no request for changing the README format. Especially for technical documentation, rst, docbook or asciidoc are a much better option. However, since the Nextcloud app store uses the keep-a-changelog format, users will get the changes once they update your app.

(and it also makes my life easier, figuring out the [changes for all of the Nextcloud apps](https://github.com/aszlig/avonc/commit/8b9356983f9c1e657eaf6845aaf724d9441bf060))

**Comment by cweiske** [comment]
This is why I wrote

> I will not introduce a second markup format in this repository
