### ISSUE TITLE
Titled blank notes cause error

### ISSUE THREAD

**Issue by nerdy-sam** [cweiske/grauphel#8]
Tomboy 1.15.4
Tomdroid 0.7.5
Grauphel 0.2.0
owncloud 7.0.2
postgresql 9.4

I could not get all my notes to sync from tomboy to grauphel and tomdroid would say sync complete with zero notes. Upon looking at the owncloud log I see this...

https://gist.github.com/mitzip/bf9a2d2542a7b1940191

It is a titled, but blank note. I started it and never added anything to it. I deleted that note and all devices started working.

**Comment by cweiske** [comment]
Fixed. Will be in 0.3.0 or 0.2.1.

**Comment by cweiske** [comment]
0.2.1 with the fix is released.

**Comment by nerdy-sam** [comment]
you're awesome and your software is much appreciated... it adds tremendous value to owncloud, good job
