### ISSUE TITLE
Sync with Tomboy/Tomdroid works on WiFi but not over 4G mobile network - HTTP/1.1 401 Unauthorized

### ISSUE THREAD

**Issue by praet0ri4n** [cweiske/grauphel#82]
Hi,

I am getting a "Error parsing response from Online Synchronization" against dockerized Nextcloud 18 + grauphel Tomboy Web server app behind nginx proxy.
The weird part is that synchronization works over WiFi, but not over 4g mobile network.

logcat and Tomboy logs show simlar erros:
adb logcat:

08-14 23:22:45.255 16223 16629 I WebConnection: Sending http-header: X-Tomboy-Client: org.tomdroid v0.7.5, build 14, Android v7.0, HUAWEI/FRD-L09
08-14 23:22:45.292 431 1337 I gralloc : alloc_device_alloc:564: Alloc handle(0x7f08a35900): interfmt=1, stride=1088, size=2752512, usage=0x933
08-14 23:22:45.319 431 1337 I gralloc : alloc_device_alloc:564: Alloc handle(0x7f08a47200): interfmt=1, stride=1088, size=2752512, usage=0x933
08-14 23:22:45.331 431 1432 I gralloc : alloc_device_alloc:564: Alloc handle(0x7f03280300): interfmt=1, stride=1088, size=2752512, usage=0x933
08-14 23:22:45.475 16223 16629 W DefaultRequestDirector: Authentication error: Unable to respond to any of these challenges: {}
08-14 23:22:45.475 16223 16629 I WebConnection: Response status : HTTP/1.1 401 Unauthorized
08-14 23:22:45.476 16223 16629 I WebConnection: Received : oauth_problem=signature_invalid&debug_sbs=GET&http%3A%2F%2F**********%3A9876%2Fowncloud%2Findex.php%2Fapps%2Fgrauphel%2Fapi%2F1.0%2Fpraet0ri4n&oauth_consumer_key%3Danyone%26oauth_nonce%3D-4471689293734163006%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1597440165%26oauth_token%3Da394fa6f96b9ef59b%26oauth_version%3D1.0
08-14 23:22:45.477 16223 16629 E SnowySyncService: Problem parsing the server response
08-14 23:22:45.477 16223 16629 E SnowySyncService: org.json.JSONException: Value oauth_problem of type java.lang.String cannot be converted to JSONObject
08-14 23:22:45.477 16223 16629 E SnowySyncService: at org.json.JSON.typeMismatch(JSON.java:111)
08-14 23:22:45.477 16223 16629 E SnowySyncService: at org.json.JSONObject.(JSONObject.java:160)
08-14 23:22:45.477 16223 16629 E SnowySyncService: at org.json.JSONObject.(JSONObject.java:173)
08-14 23:22:45.477 16223 16629 E SnowySyncService: at org.tomdroid.sync.web.SnowySyncService$3.run(SnowySyncService.java:196)
08-14 23:22:45.477 16223 16629 E SnowySyncService: at org.tomdroid.sync.SyncService$1.run(SyncService.java:170)
08-14 23:22:45.477 16223 16629 E SnowySyncService: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-14 23:22:45.477 16223 16629 E SnowySyncService: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)

The same request made ofer wifi gets:
08-14 23:25:43.253 16223 17273 I WebConnection: Sending http-header: X-Tomboy-Client: org.tomdroid v0.7.5, build 14, Android v7.0, HUAWEI/FRD-L09
08-14 23:25:43.289 431 444 I gralloc : alloc_device_alloc:564: Alloc handle(0x7f08a41500): interfmt=1, stride=1088, size=2752512, usage=0x933
08-14 23:25:43.321 431 1432 I gralloc : alloc_device_alloc:564: Alloc handle(0x7f08a40c00): interfmt=1, stride=1088, size=2752512, usage=0x933
08-14 23:25:43.347 1206 1206 I TrafficMonitor: update:rxPkts:25,txPkts:24,rxBytes:8768,txBytes:2357
08-14 23:25:43.347 1206 1206 I TrafficMonitor: start expired. level:-1
08-14 23:25:43.347 1206 1206 I TrafficMonitor: gettimer:interval=2000
08-14 23:25:43.376 430 430 E ServiceManager: try to find service failed, not allowed access from isolated processes.
08-14 23:25:43.379 4434 4449 I ServiceManager: Waiting for service SurfaceFlinger...
08-14 23:25:43.424 16223 17273 I WebConnection: Response status : HTTP/1.1 200 OK
08-14 23:25:43.425 16223 17273 I WebConnection: Received : {"user-name":"","first-name":null,"last-name":null,"notes-ref":{"api-ref":"https://:9876/owncloud/index.php/apps/grauphel/api/1.0/********/notes","href":"https://***:9876/owncloud/index.php/apps/grauphel/"},"latest-sync-revision":11,"current-sync-guid":"-5f345606277683.76428085"}
....

Does this mean, that the connection request from WiFi / 4G result in different access requests? It needs different access tokens?

**Comment by praet0ri4n** [comment]
For completeness here is the log from ubuntu tomboy notes app
...
[ERROR]: Synchronization failed with the following exception: The remote server returned an error: (401) Unauthorized.
...
This is when connected to internet via mobile phone hotspot.

Somehow grauphel can't authorize requests upon network change (wifi > 4g).
Once back on home nework the syncing works.
Does Oauth limit authorization to "known sources", or "trusted domains", or maybe one source only?

Anyway I tried to clear the tomboy and tomdroid sync settings and initiate the oauth authorization from scrach over 4g. This leads to same 401 error on nextcloud server even not allowing the oauth process to start..

I will try to look into request headers on server side to compare contents. Can the mobile network be stripping som data from requests?

**Comment by praet0ri4n** [comment]
The http request header revealed some extra header info added by my nginx reverse proxy, like
X-Real-IP: ....
leading to response
...
 [truncated]oauth_problem=signature_invalid&debug_sbs=GET&http%3A%2F%2F***%2Findex.php%2Fapps%2Fgrauphel%2Fapi%2F1.0%2Fpraet0ri4n&oauth_consumer_key%3Danyone%26oauth_nonce%3D-2211826031882362032%26oauth_signature_method%3DHMAC-SHA1
...

Now I reduced site nginx conf to
....
proxy_set_header Host $http_host;
proxy_set_header X-Forwarded-For $remote_addr;
proxy_set_header X-Forwarded-Proto $scheme;
....
and sync works on all networks

Just for reference. Thanks for the awesome grauphel plugin! Closing..

**Comment by cweiske** [comment]
Thanks for documenting your solution.
