### ISSUE TITLE
Support Request: oauth failure

### ISSUE THREAD

**Issue by mwerle** [cweiske/grauphel#85]
Over the weekend I upgrade my nextcloud install from 15 (!) to 20.

Everything went smoothly until NC20 - lots of broken apps and Tomboy/Tomdroid could no longer sync.

Using "Fiddler" I captured the following response from the server (there's nothing in the Nextcloud logs, even with logging level 0):

oauth_problem=signature_invalid&debug_sbs=POST&%01%3A%2F%2F%01%01&oauth_callback%3Dhttp%253A%252F%252Flocalhost%253A8000%252Ftomboy-web-sync%252F%26oauth_consumer_key%3Danyone%26oauth_nonce%3D3930696%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1610866517%26oauth_version%3D1.0

I rolled back to NC19 but Grauphel sync is still broken.

Any hints on how to investigate further and fix this? The capture above shows the "POST" url might be corrupted inside the app (0x01 :// 0x01 0x01)

**Comment by cweiske** [comment]
- Someone else's problem was the nginx reverse proxy settings: https://github.com/cweiske/grauphel/issues/82
- Another one's problem was incompatible php and php-oauth versions: https://github.com/cweiske/grauphel/issues/72#issuecomment-519173520
- Another problem was that a new nextcloud version used pretty urls, while the client used the old one with index.php: https://github.com/cweiske/grauphel/issues/46#issuecomment-335171835

I fear that I cannot help any further and you have to investigate yourself.

**Comment by mwerle** [comment]
Thanks - it was due to #72; thanks "stable" Debian...  (I think this is the first time a stable version of Debian had such a fundamental issue which wasn't fixed asap in my experience).

Instead of compiling my own I downloaded a binary-compatible snapshot:
http://snapshot.debian.org/package/php-oauth/2.0.5%2B1.2.3-1/#php-oauth_2.0.5:2b:1.2.3-1
