### ISSUE TITLE
Unknown token: temp / 

### ISSUE THREAD

**Issue by RSlegers** [cweiske/grauphel#88]
When i want to connect Tomboy (Linux) to NextCloud/grauphel I get the screen to name the connection, after that i need to press "Yes, Authorize" twice, (the fisrt time the screen only reloads? (filled in name stays), after the second press is get "Unknown token: temp /"

Here is my log from Nextcloud (at least the part that is added when i get the error)

`{"reqId":"zLM6dhgXEfjKt9DIMWSt","level":3,"time":"2021-02-07T18:11:52+00:00","remoteAddr":"ipv6:ipv6:ipv6:ipv6:ipv6:ipv6:ipv6:ipv6","user":"admin","app":"PHP","method":"POST","url":"/index.php/apps/grauphel/oauth/confirm","message":{"Exception":"Error","Message":"Undefined property: OCA\\Grauphel\\Lib\\Response\\ErrorResponse::$tokenKey at /var/customers/webs/User/nextcloud.mydomain.nl/apps/grauphel/controller/oauthcontroller.php#158","Code":0,"Trace":[{"file":"/var/customers/webs/User/nextcloud.mydomain.nl/apps/grauphel/controller/oauthcontroller.php","line":158,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[8,"Undefined property: OCA\\Grauphel\\Lib\\Response\\ErrorResponse::$tokenKey","/var/customers/webs/User/nextcloud.mydomain.nl/apps/grauphel/controller/oauthcontroller.php",158,{"token":{"__class__":"OCA\\Grauphel\\Lib\\Response\\ErrorResponse"},"oauth":{"__class__":"OCA\\Grauphel\\Lib\\OAuth"}}]},{"file":"/var/customers/webs/User/nextcloud.mydomain.nl/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"confirm","class":"OCA\\Grauphel\\Controller\\OauthController","type":"->","args":[]},{"file":"/var/customers/webs/User/nextcloud.mydomain.nl/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"deps":{"frontend":null,"noteStorage":null,"oauthStorage":null,"urlGen":{"__class__":"OC\\URLGenerator"},"tokens":{"__class__":"OCA\\Grauphel\\Lib\\TokenStorage"},"__class__":"OCA\\Grauphel\\Lib\\Dependencies"},"__class__":"OCA\\Grauphel\\Controller\\OauthController"},"confirm"]},{"file":"/var/customers/webs/User/nextcloud.mydomain.nl/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"deps":{"frontend":null,"noteStorage":null,"oauthStorage":null,"urlGen":{"__class__":"OC\\URLGenerator"},"tokens":{"__class__":"OCA\\Grauphel\\Lib\\TokenStorage"},"__class__":"OCA\\Grauphel\\Lib\\Dependencies"},"__class__":"OCA\\Grauphel\\Controller\\OauthController"},"confirm"]},{"file":"/var/customers/webs/User/nextcloud.mydomain.nl/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OauthController","confirm",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"grauphel.oauth.confirm"}]},{"file":"/var/customers/webs/User/nextcloud.mydomain.nl/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/grauphel/oauth/confirm"]},{"file":"/var/customers/webs/User/nextcloud.mydomain.nl/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/customers/webs/User/nextcloud.mydomain.nl/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36","version":"20.0.7.1"}
`

**Comment by RSlegers** [comment]
OAuth info from phpinfo.php:

- PLAINTEXT support | enabled
- RSA-SHA1 support | enabled
- HMAC-SHA1 support | enabled
- Request engine support | php_streams
- version | 2.0.5

**Comment by cweiske** [comment]
Did you ever solve this problem?
Also, which Nextcloud and PHP versions are this?

**Comment by RSlegers** [comment]
No, i did not yet solve this problem.

NextCloud version:  21.0.1
PHP version: 7.3.19

**Comment by cweiske** [comment]
grauphel is not compatible with Nextcloud 21.

**Comment by afteroot** [comment]
Any updates on this ?
And will grauphel compatible with Nextcloud 21 in future?
