### ISSUE TITLE
Seeking new maintainer (or funding for standalone version)

### ISSUE THREAD

**Issue by cweiske** [cweiske/grauphel#89]
I personally do not use grauphel anymore and thus have no reason to maintain it any longer.
For each Nextcloud release it must be tested, updated and re-released. Big changes (#87) are necessary to make it compatible with Nextcloud 21 as well.

The last real changes to grauphel were done in 2018 (version 0.7.0), and since then the changes were only to make it compatible with Nextcloud 15...20. The application itself is complete since 4 years, but unfortunately the foundations are constantly moving.
The original grauphel was a standalone application, but I converted it to a owncloud/nextcloud extension so that I can rely on its login and user management. From today's perspective this was a mistake; a standalone version would still work today and not require unnecessary maintenance.

----

I'd like to hand grauphel over to a new maintainer that keeps it compatible with the latest Nextcloud versions.

Alternatively, I could make a standalone version of grauphel that works without nextcloud if I get money to work on this task - 1000€.

Please write a comment here if you'd like to take over the project, or how much you're willing to contribute to the standalone version's fund.

**Comment by cweiske** [comment]
Nobody replied here. I am archiving this repository. Contact me by e-mail if necessary.

**Comment by cweiske** [comment]
@grosjo is the new maintainer.

**Comment by mwerle** [comment]
Thank you for taking this over, @grosjo.

And thank you very much for creating and maintaing Grauphel in the first place, @cweiske.

**Comment by grosjo** [comment]
@cweiske  Can you also move the ownerhsip of the app in NexCLoud store to 'grosjo' ?
https://apps.nextcloud.com/apps/grauphel
THank you

**Comment by cweiske** [comment]
I've sent a mail with the keys to you.
