### ISSUE TITLE
Tomboy synchronizes sometimes from old to new

### ISSUE THREAD

**Issue by xylo** [cweiske/grauphel#9]
Hi Christian,

I edited a note X on my PC and synchronized it with our Tomboy server.  The first synchronization worked fine.  But when I edit the note again and try to synchronize it with the server Tomboy insists on replacing my newer local version with the older one from the server.

Both computers have the same time zone and nearly the same time.  I could reproduce the behavior several times and it is still present.

**Comment by cweiske** [comment]
We couldn't reproduce that together. Re-open the issue if you can reproduce the problem.

**Comment by cweiske** [comment]
I found it in the owncloud log; it's the same cause as bug #8 .
