### ISSUE TITLE
cannot be installed on Nextcloud 23: "The appinfo/database.xml file is not longer supported"

### ISSUE THREAD

**Issue by monperrus** [cweiske/grauphel#90]
Hi,

FYI, grauphel does not run on Nextcloud 23, the error message at installation time is `The appinfo/database.xml file is not longer supported. Used in grauphel`

Thanks!

**Comment by grosjo** [comment]
@monperrus Can you try with latest release (1.0.0) ?

**Comment by grosjo** [comment]
Version 1.0.3 (from the app store) shall resolve the pb

**Comment by monperrus** [comment]
Thanks a lot @grosjo
