### ISSUE TITLE
app.php is not loaded... 

### ISSUE THREAD

**Issue by saintfrater** [cweiske/grauphel#91]
Hello, 

I've upgraded to version 1.0.3 then upgraded to OC version 23, but from now, the application isn't shown (but seems to work for sync') and flood the log with following:

```
[grauphel] Error: /appinfo/app.php is not loaded when \OCP\AppFramework\Bootstrap\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.

GET /apps/logreader/poll?lastReqId=BXqRkJdVlOF4PrEsEGRS
from xxxx:xxxx:xxxx:xxxx::xxxx by frater at 2022-01-03T18:24:24+01:00
```

I've worked around by renaming the app.php, but the application won't show itself in the UI.

what should I do ?

**Comment by grosjo** [comment]
Can you upgrade to version 1.0.4 ?

**Comment by saintfrater** [comment]
> Can you upgrade to version 1.0.4 ?

I've just updated to the new version:
![image](https://user-images.githubusercontent.com/13979047/148066314-2a42c10e-d3fd-436d-b62b-450672c1ccb9.png)

Version updated without success... still not shown in the "application bar":
![image](https://user-images.githubusercontent.com/13979047/148066098-b3cc3745-2534-4b7a-8b6f-0cc5498b7b69.png)

and the log still flooded:
![image](https://user-images.githubusercontent.com/13979047/148066174-9cab6a0e-60d0-4392-accb-5d491498d398.png)

Some infos about my server is a debian 11 (bullseye) fully updated with PHP 7.4.25, mysql server 10.5.12

As I've mentionned before the application is fully working if you reach it via the url): 

![image](https://user-images.githubusercontent.com/13979047/148068510-f8692890-8952-4d47-831a-51ffd3d1778b.png)

I don't know the NC framework, but if you need any logs or infos tell me :p

regards,

**Comment by grosjo** [comment]
Please kindly try version 1.0.5

**Comment by saintfrater** [comment]
It's working normally... (icon show up) thank you for the fix, however, it' seems to have some remarke about search provider:

[PHP] Error: Declaration of OCA\Grauphel\Search\Provider::search($query) must be compatible with OCP\Search\IProvider::search(OCP\IUser $user, OCP\Search\ISearchQuery $query): OCP\Search\SearchResult at /home/httpd/domain/nextcloud/apps/grauphel/lib/Search/Provider.php#44

it's minor :D

again thank you

**Comment by grosjo** [comment]
Kindly try Version 1.06

**Comment by saintfrater** [comment]
Fixed...

thank you man :)
