### ISSUE TITLE
Install error Unknown column type "timestamp" requested

### ISSUE THREAD

**Issue by romseguy** [cweiske/grauphel#92]
Hello

Nextcloud 23.0.0
Grauphel 1.0.4
PHP 7.3
Ubuntu 18.04

When enabling the app from https://myhost.com/index.php/settings/apps/tools/grauphel

> An error occured during the request. Unable to proceed.
> Unknown column type "timestamp" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgotten to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information.

Any idea why ?

**Comment by grosjo** [comment]
Linked to #91

**Comment by grosjo** [comment]
Please kindly confirm that is fixed in recent release (1.0.6)

**Comment by romseguy** [comment]
![image](https://user-images.githubusercontent.com/109238/148932810-e320b007-0656-435e-9c8f-bc8cd39f3b8f.png)

**Comment by grosjo** [comment]
@romseguy 
Is that still current ?

**Comment by grosjo** [comment]
Looks fixed
