### ISSUE TITLE
nextcloud 20 update to 1.0.1 not possible

### ISSUE THREAD

**Issue by vjuergens** [cweiske/grauphel#93]
The automatic update reports an error. A manual update with the download for version 1.0.1 indicates that Grauphel 1.0.2 requires Nextcloud 22.

**Comment by grosjo** [comment]
Is that still current ?

**Comment by vjuergens** [comment]
Just tried to update. Same error as described.

**Comment by grosjo** [comment]
do you have 1.0.6 in your nextcloud (and not 1.0.1) ?

**Comment by vjuergens** [comment]
Roundcube!? You mean nextcloud. I still have the last version, before you adopt this software,  0.7.6 in nextcloud 20.0. I think the solution is quite simple, please adjust the manifest of the grauphel version for nextcloud 20.0 to expect next nextcloud 20.0 and not 22.0.

**Comment by grosjo** [comment]
Please check again on nextcloud

**Comment by vjuergens** [comment]
the automatic update still will use the 1.0.1 Version. In the nextcloud store, I see your update 1.0.7 with the correct requirements. I think I have to wait until my nextcloud instance will reload the the software store index.

**Comment by vjuergens** [comment]
Just got a notification that 1.0.7 is available. The update failed due to a wrong packed package. After the update the plugin directory structure is wrong:

1.0.7
drwxr-xr-x www-data/www-data 0 2022-03-12 20:57 grauphel/
drwxr-xr-x www-data/www-data 0 2022-03-12 20:57 grauphel/grauphel/
-rw-r--r-- www-data/www-data 4896 2022-03-12 20:57 grauphel/grauphel/README.rst
drwxr-xr-x www-data/www-data    0 2022-03-12 20:57 grauphel/grauphel/tools/
-rw-r--r-- www-data/www-data 14339 2022-03-12 20:57 grauphel/grauphel/tools/database.xsd
-rw-r--r-- www-data/www-data   308 2022-03-12 20:57 grauphel/grauphel/tools/convert.php
-rw-r--r-- www-data/www-data 24612 2022-03-12 20:57 grauphel/grauphel/tools/info.xsd
-rw-r--r-- www-data/www-data  1440 2022-03-12 20:57 grauphel/grauphel/build.xml
drwxr-xr-x www-data/www-data     0 2022-03-12 20:57 grauphel/grauphel/news/
-rw-r--r-- www-data/www-data   137 2022-03-12 20:57 grauphel/grauphel/news/CHANGELOG.md
-rw-r--r-- www-data/www-data 34520 2022-03-12 20:57 grauphel/grauphel/LICENSE
drwxr-xr-x www-data/www-data     0 2022-03-12 20:57 grauphel/grauphel/templates/

0.7.6

drwxr-xr-x www-data/www-data 0 2021-01-22 18:53 grauphel/
-rw-r--r-- www-data/www-data 5497 2021-01-22 18:53 grauphel/README.rst
drwxr-xr-x www-data/www-data    0 2021-01-22 18:53 grauphel/tools/
-rw-r--r-- root/root        14339 2021-12-27 11:55 grauphel/tools/database.xsd
-rw-r--r-- www-data/www-data  308 2021-01-22 18:53 grauphel/tools/convert.php
-rw-r--r-- root/root        24612 2021-12-27 11:55 grauphel/tools/info.xsd
-rw-r--r-- root/root         1440 2021-12-27 11:55 grauphel/build.xml
drwxr-xr-x root/root            0 2022-01-03 07:41 grauphel/news/
-rw-r--r-- root/root          137 2022-01-03 07:41 grauphel/news/CHANGELOG.md
-rw-r--r-- root/root        34520 2021-12-27 11:55 grauphel/LICENSE
drwxr-xr-x www-data/www-data    0 2021-01-22 18:53 grauphel/templates/


.

**Comment by vjuergens** [comment]
The update to 1.0.8 works fine, no further issues.

**Comment by grosjo** [comment]
Are you using nextcloud 22 ?

**Comment by vjuergens** [comment]
Nope, still on my old Server: Nextcloud 20.0.14

Von: Joan Moreau
Gesendet: Dienstag, 11. Oktober 2022 09:22
An: grosjo/nextcloud-grauphel
Cc: vjuergens; State change
Betreff: Re: [grosjo/nextcloud-grauphel] nextcloud 20 update to 1.0.1 notpossible (Issue #93)



Are you using nextcloud 22 ?
